//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRoster.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public int employee_id { get; set; }
        public string booking_type_code { get; set; }
        public string comment { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public bool deleted_flag { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
