//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRoster.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleType
    {
        public RoleType()
        {
            this.Employees = new HashSet<Employee>();
            this.RoleTypes1 = new HashSet<RoleType>();
        }
    
        public int roletype_id { get; set; }
        public string roletype_name { get; set; }
        public Nullable<int> reports_to_id { get; set; }
        public int max_per_deptcrew { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<RoleType> RoleTypes1 { get; set; }
        public virtual RoleType RoleType1 { get; set; }
    }
}
